export type MenuItem = {
    name: string;
    description?: string;
    price?: string;
    tags?: string[];
};

export type MenuCategory = {
    id: string;
    title: string;
    image: string; // New image property
    description?: string;
    note?: string;
    items: MenuItem[];
};

export const MENU_DATA: MenuCategory[] = [
    {
        id: "lunch-plates",
        title: "Lunch Plates",
        image: "/Daily pasta and chicken fritters.jpg",
        description: "ランチプレート - ご注文のお客様はケーキ・ジェラートが＋¥200(税込)",
        items: [
            {
                name: "サッチプレートランチ",
                description: "日替わりパスタ＆チキンのフリット / サラダ、パン、ドリンク付き / お好みのソース（オイル、トマト、クリーム）に変更OK",
            },
            {
                name: "ガーリックシュリンププレート",
                description: "サッチ創業以来不動の人気メニュー！！ / サラダ、ライス、ドリンク付き",
            },
        ],
    },
    {
        id: "lunch-meat",
        title: "Lunch - Meat Dish",
        image: "/Lunch - meat dishes -.jpg",
        description: "ランチ 〜肉料理〜",
        note: "※サラダ・ライスorパン・ドリンク付き",
        items: [
            { name: "イタリアンハンバーグ", description: "デミグラス or トマト" },
            { name: "肉おでん" },
            { name: "チキンステーキ", description: "オリジナルデミグラス or イタリアントマトソース" },
            { name: "氷見牛サーロインステーキ（200g）" },
        ],
    },
    {
        id: "lunch-pasta",
        title: "Lunch - Pasta & Risotto",
        image: "/Lunch - 1 dish dish.jpg",
        description: "ランチ 〜1皿料理〜",
        note: "スパゲッティ or ニョッキ or ペンネ or リゾットからお選びいただけます。 ※1.5倍はプラス￥500",
        items: [
            { name: "ベーコンと野菜のアーリオ・オーリオ" },
            { name: "ジェノベーゼ" },
            { name: "ポモドーロ・モッツァレラ" },
            { name: "明太子クリーム" },
            { name: "カルボナーラ" },
            { name: "ボンゴレホワイトスープ" },
            { name: "カニトマトクリーム" },
            { name: "ガーリックシュリンプ" },
        ],
    },
    {
        id: "salad",
        title: "Green Salad",
        image: "/green salad.jpg",
        description: "グリーンサラダ",
        note: "※オリジナルドレッシング：バルサミコセサモ or 和風",
        items: [
            { name: "シーザーサラダ" },
            { name: "Greeeeeeenサラダ" },
            { name: "キトキト鮮魚サラダ" },
            { name: "生ハムとフレッシュ野菜のサラダ" },
            { name: "ベーコンとキノコのソテーサラダ" },
            { name: "炭火焼ローストビーフサラダ" },
        ],
    },
    {
        id: "side-cold",
        title: "Cold Appetizers",
        image: "/Cold side dishes.jpg",
        description: "冷製サイドメニュー",
        items: [
            { name: "タラモサラダ" },
            { name: "カプレーゼ" },
            { name: "彩り野菜のピクルス" },
            { name: "炭火焼ローストビーフ" },
            { name: "生ハムとチーズの盛り合わせ" },
            { name: "本日のカルパッチョ" },
        ],
    },
    {
        id: "side-hot",
        title: "Hot Appetizers",
        image: "/Hot side dishes.jpg",
        description: "温製サイドメニュー",
        items: [
            { name: "肉おでん" },
            { name: "フライドポテトお子様ver." },
            { name: "大人のフライドポテト" },
            { name: "本日のアヒージョ" },
            { name: "自家野菜のカポナータ" },
            { name: "地鶏のフリット" },
            { name: "アサリとムール貝の白ワイン蒸し" },
            { name: "ソーセージ＆大人のフライドポテト" },
            { name: "パンチェッタのグリル" },
            { name: "チーズフォンデュ" },
            { name: "ガーリックたこ唐" },
            { name: "ガーリックシュリンプ" },
        ],
    },
    {
        id: "pizza",
        title: "Pizza",
        image: "/Pizza & Pasta.jpg",
        description: "ピザ",
        items: [
            { name: "マルゲリータ" },
            { name: "ベーコンエッグ" },
            { name: "ジェノベーゼ生ハム" },
            { name: "ミックスピザ" },
            { name: "カポナータピザ" },
            { name: "ボッタルガ" },
            { name: "クアトロフォロマッジ" },
            { name: "鮮魚ピザ" },
        ],
    },
    {
        id: "grand-pasta",
        title: "Grand Menu Pasta",
        image: "/main3.jpg",
        description: "パスタ - ディナー",
        note: "※『乾麺』『生パスタ』『ニョッキ』『ペンネ』『リゾット』から選択可 / 1.5倍は+500円 / 辛さ調整・ニンニク減量可",
        items: [
            { name: "ペペロンチーノ", tags: ["Spicy"] },
            { name: "ナポリタン" },
            { name: "アラビアータ", tags: ["Spicy"] },
            { name: "ベーコンと野菜のアーリオ・オーリオ" },
            { name: "ポモドーロモッツァレラ" },
            { name: "ジェノベーゼ" },
            { name: "明太子クリーム" },
            { name: "ボンゴレビアンコ" },
            { name: "ボンゴレロッソ" },
            { name: "カルボナーラ" },
            { name: "ボンゴレホワイトスープ" },
            { name: "カニトマトクリーム" },
            { name: "ペスカトーレビアンコ" },
            { name: "ガーリックシュリンプパスタ" },
            { name: "ゴルゴンゾーラチーズクリーム" },
        ],
    },
    {
        id: "sides-carb",
        title: "Bread & Rice & Soup",
        image: "/Bread, rice, soup.jpg",
        description: "パン・ライス・スープ",
        items: [
            { name: "ライス" },
            { name: "アンチョビ・ガーリックトースト" },
            { name: "パン" },
            { name: "ガーリックトースト" },
            { name: "パン盛り合わせ" },
            { name: "ミネストローネ" },
            { name: "ガーリックスープ" },
        ],
    },
    {
        id: "main-dish",
        title: "Main Dish",
        image: "/Single dish.jpg",
        description: "単品ディッシュ",
        items: [
            { name: "チキンステーキ", description: "デミグラス or トマト" },
            { name: "イタリアンハンバーグ", description: "デミグラス or トマト" },
            { name: "地鶏のステーキ" },
            { name: "とろとろビーフシチュー（200ｇ）" },
            { name: "牛ステーキのタリアータ（200ｇ）" },
            { name: "氷見牛サーロインステーキ（200ｇ）" },
        ],
    },
    {
        id: "dolce",
        title: "Dolce & Gelato",
        image: "/Sweets (desserts).jpg",
        description: "スウィーツ（デザート）",
        items: [
            { name: "本日のドルチェ" },
            { name: "本日のシフォンケーキ" },
            { name: "ティラミス" },
            { name: "本日のジェラート" },
            { name: "グランピスタチオ" },
            { name: "プレミアムミルク" },
            { name: "チョコレート" },
            { name: "八尾牛乳ソフトクリーム", description: "カップ/コーン ※テイクアウトOK" },
            { name: "各種フロート", description: "コーヒー/コーラ/クリームソーダ/ブラッドオレンジ/ノンアルコール" },
        ],
    },
    {
        id: "alcohol",
        title: "Alcohol",
        image: "/Alcoholic drinks.jpg",
        description: "アルコールドリンク",
        items: [
            { name: "生ビール", description: "285ml / 570ml" },
            { name: "日本酒", description: "おわら娘 / 三笑楽 / 風の雫" },
            { name: "焼酎", description: "ゴッドファーザー（麦）/ 紫の赤兎馬（芋）/ ゴッドファーザーリターンズ（芋）" },
            { name: "梅酒", description: "立山梅酒 / あらごし梅酒" },
            { name: "ウィスキー", description: "ジムビーム / 宮城狭 / 知多" },
        ],
    },
    {
        id: "cocktail",
        title: "Cocktail",
        image: "/main4.jpg",
        description: "カクテル",
        items: [
            { name: "シチリアレモンサワー" },
            { name: "カシスウーロン" },
            { name: "カシスソーダ" },
            { name: "カシスオレンジ" },
            { name: "カンパリソーダ" },
            { name: "カンパリオレンジ" },
            { name: "ピーチウーロン" },
            { name: "ピーチソーダ" },
            { name: "ファジーネーブル" },
            { name: "ジンバック" },
            { name: "ジントニック" },
            { name: "ウォッカトニック" },
            { name: "ブルドック" },
            { name: "シャンディガフ" },
        ],
    },
    {
        id: "softdrink",
        title: "Soft Drink / Coffee",
        image: "/Soft drinks:coffee.jpg",
        description: "ソフトドリンク / コーヒー",
        items: [
            { name: "ウーロン茶" },
            { name: "ブドウジュース" },
            { name: "オレンジジュース" },
            { name: "グレープフルーツジュース" },
            { name: "カルピス" },
            { name: "ジンジャーエール" },
            { name: "コカ・コーラ" },
            { name: "レモンジュース" },
            { name: "アイスピーチティー" },
            { name: "トニックウォーター" },
            { name: "ブラッドオレンジジュース" },
            { name: "ノンアルコールビール" },
            { name: "コーヒー", description: "Hot or Ice" },
            { name: "エスプレッソ" },
            { name: "紅茶", description: "Hot or Ice" },
            { name: "カプチーノ", description: "Hot or Ice" },
            { name: "カフェラテ", description: "Hot or Ice" },
        ],
    },
    {
        id: "course",
        title: "Course Menu",
        image: "/Course:All-you-can-drink.jpg",
        description: "コース / 飲み放題",
        items: [
            { name: "ライトコース", price: "￥3,000", description: "定番メニューのフルコースを低価格でお楽しみいただけます。" },
            { name: "ミディアムコース", price: "￥4,000", description: "ライトコースより前菜が多く、より自家野菜を楽しんでいただけるコースです。" },
            { name: "フルボディコース", price: "￥5,000", description: "最上級のコース。自家野菜と厳選された素材をふんだんに使い、始まりから終わりまで楽しんでいただける究極のコースです。" },
            { name: "メモリアルコース", price: "￥3,500", description: "ライトコースの内容で、デザートを記念日仕様に。記念日の文字入れも併せてお伝え下さい。" },
        ],
    },
];
